// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SillyMonthsML.Model
{
    public class ModelInput
    {
        [ColumnName("Input"), LoadColumn(0)]
        public float Input { get; set; }


        [ColumnName("Result"), LoadColumn(1)]
        public float Result { get; set; }


    }
}
